import type { GetStaticPaths, GetStaticProps } from "next";
import Link from "next/link";
import Seo from "@/components/Seo";
import { type ProjectDetail, getProjectLinks, getProjectPageData, getProjectStaticPaths } from "@/data/projects";
import { getCaseStudyBySlug, getCaseStudyHref } from "@/data/caseStudies";

export default function ProjectDetailPage({ project }: { project: ProjectDetail }) {
  return <main className="page-shell py-14 sm:py-20"><Seo title={`${project.title} | 장석환 Frontend Developer`} description={project.summary} path={`/projects/${project.id}`} article /><article className="max-w-3xl"><Link href={project.category === "selected" ? "/projects" : "/projects/archive"} className="text-link text-sm">← {project.category === "selected" ? "선별 개인 프로젝트" : "Project Archive"}</Link><header className="mb-10 mt-7 border-b border-slate-200 pb-8"><p className="eyebrow">{project.category === "selected" ? "Selected Personal Project" : "Archive"}</p><h1 className="page-heading mt-4">{project.title}</h1><p className="mt-6 text-lg leading-8 text-slate-600">{project.summary}</p><dl className="mt-7 space-y-3 text-sm"><div><dt className="inline font-semibold">기간·확인 범위 </dt><dd className="inline text-slate-600">{project.period}</dd></div><div><dt className="inline font-semibold">역할 </dt><dd className="inline text-slate-600">{project.role}</dd></div>{project.techStack.length > 0 && <div><dt className="inline font-semibold">기술 </dt><dd className="inline text-slate-600">{project.techStack.join(" · ")}</dd></div>}</dl>{getProjectLinks(project).length > 0 && <div className="mt-7 flex flex-wrap gap-3">{getProjectLinks(project).map((link) => <a href={link.href} key={link.href} target="_blank" rel="noopener noreferrer" className="button-secondary">{link.label} <span aria-hidden="true" className="ml-2">↗</span><span className="sr-only"> 새 탭</span></a>)}</div>}</header><section><h2 className="text-xl font-bold">문제</h2><p className="mt-4 leading-8 text-slate-600">{project.problem}</p></section>{([{ title: "주요 기여", items: project.contribution }, { title: "결과", items: project.result }, { title: "검증 범위와 한계", items: project.limitations }]).filter(({ items }) => items.length).map(({ title, items }) => <section key={title} className="mt-10"><h2 className="text-xl font-bold">{title}</h2><ul className="prose-list mt-4">{items.map((item) => <li key={item}>{item}</li>)}</ul></section>)}{project.relatedCaseStudies.length > 0 && <section className="mt-12 border-t border-slate-200 pt-8"><h2 className="text-lg font-bold">같은 주제의 업무 기록</h2><p className="mt-2 text-sm text-slate-500">개인 프로젝트와 업무 구현은 별개의 작업입니다.</p><ul className="mt-4 space-y-3">{project.relatedCaseStudies.map((slug) => <li key={slug}><Link className="text-link leading-7" href={getCaseStudyHref(getCaseStudyBySlug(slug)!)}>{getCaseStudyBySlug(slug)?.title}</Link></li>)}</ul></section>}</article></main>;
}

export const getStaticPaths: GetStaticPaths = async () => ({ paths: getProjectStaticPaths(), fallback: false });
export const getStaticProps: GetStaticProps<{ project: ProjectDetail }> = async ({ params }) => getProjectPageData(params?.id);
